// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAri1bwE0WJrDIrvwU6RGmLJawWtZVGa18',
    appId: '1:2292447531:web:a96d228bdddbe5a76dad6e',
    messagingSenderId: '2292447531',
    projectId: 'shareex-a59a3',
    authDomain: 'shareex-a59a3.firebaseapp.com',
    storageBucket: 'shareex-a59a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQN0FQTAmmrRpigc4QWO9vbpSDyiSfgs8',
    appId: '1:2292447531:android:a4e0cc1942ba1f4f6dad6e',
    messagingSenderId: '2292447531',
    projectId: 'shareex-a59a3',
    storageBucket: 'shareex-a59a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-OhA7zSa3N4A1jUTZW-2CPOWLLX4wi9s',
    appId: '1:2292447531:ios:58b5806a60035bb96dad6e',
    messagingSenderId: '2292447531',
    projectId: 'shareex-a59a3',
    storageBucket: 'shareex-a59a3.appspot.com',
    iosBundleId: 'com.example.shareex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-OhA7zSa3N4A1jUTZW-2CPOWLLX4wi9s',
    appId: '1:2292447531:ios:d436073d8b0ea71a6dad6e',
    messagingSenderId: '2292447531',
    projectId: 'shareex-a59a3',
    storageBucket: 'shareex-a59a3.appspot.com',
    iosBundleId: 'com.example.shareex.RunnerTests',
  );
}
